# Generated by Django 2.0.5 on 2018-05-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Korean', models.CharField(max_length=10)),
                ('English', models.CharField(max_length=20)),
                ('Uzb', models.CharField(max_length=20)),
                ('Russian', models.CharField(max_length=20)),
            ],
        ),
    ]
